---
- name: Get ansible facts
  hosts: switches
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Show interface status
      ios_command:
        commands:
          - show interfaces status

