#Configure DHCP (pools need to be available) & DHCP excluded addresses (dhcp_excluded has to be available)
---
- name: DHCP CONFIG
  cisco.ios.ios_config:
    before: "ip dhcp pool {{ item.0.name }}"
    lines:
      - "network {{ item.1.network }}"
      - "default-router {{ item.1.default_router }}"
    parents: "ip dhcp pool {{ item.0.name }}"
  with_subelements:
    - "{{ pools }}"
    - subconfigurations
  when: pools is defined

- name: Excluded DHCP-addresses
  cisco.ios.ios_config:
    lines:
    - ip dhcp excluded-address {{ item }}
  with_items: "{{ dhcp_excluded }}"
  when: dchp_excluded is defined