---
- name: configure subinterfaces
  ios_config:
    before: "interface {{ item.0.name }}.{{ item.1.vlan_id }}"
    lines: 
      - "encapsulation dot1Q {{ item.1.vlan_id }}"
      - "ip address {{ item.1.ip }} {{ item.1.subnet }}"
    after: 
      - no shutdown
    match: strict
    parents: "interface {{ item.0.name }}.{{ item.1.vlan_id }}"
  with_subelements:
        - "{{ interfaces }}"
        - subinterfaces
  when: interfaces is defined

- name: No shutdown on interface
  cisco.ios.ios_interfaces:
    config:
    - name: "{{ item.0.name }}"
      enabled: true
  with_subelements:
        - "{{ interfaces }}"
        - subinterfaces
  when: interfaces is defined
  
          
      