---
# tasks file for firewalls
# - include_tasks: /home/killian/Network-Automation/roles/firewalls/tasks/settings.yml
 - include_tasks: /home/killian/Network-Automation/roles/firewalls/tasks/vlan.yml
