---
- name: Configure VPN SSL portal
  fortios_vpn_ssl_web_portal:
    vdom: "{{ vdom }}"
    state: "present"
    vpn_ssl_web_portal:
      name: "sslvpn"
      tunnel_mode: "enable"
      split_tunneling: "enable"
      ip_pools:
        - name: "SSLVPN_TUNNEL_ADDR1"
      web_mode: "enable"
      heading: "SSL-VPN Portal"

- name: Create User
  fortios_user_local:
    vdom: "{{ vdom }}"
    state: "present"
    user_local:
      name: "SSLADMIN"
      passwd: "ssladmin"


- name: Create group for all SSL-Users
  fortios_user_group:
    vdom: "{{ vdom }}"
    state: "present"
    user_group:
      name: "SSL-GROUP"
      group_type: "firewall"
      member:
        - name: "SSLADMIN"

- name: Configure VPN SSL settings
  fortios_vpn_ssl_settings:
    vdom: "{{ vdom }}"
    vpn_ssl_settings:
      source_interface:
         -
            name: "wan1"
      port: "4433"
      servercert: "Fortinet_Factory"
      idle_timeout: "300"
      default_portal: "web-access"
      tunnel_ip_pools:
         -
            name: "SSLVPN_TUNNEL_ADDR1"
      tunnel_ipv6_pools:
         -
            name: "SSLVPN_TUNNEL_IPv6_ADDR1"
      source_address:
         -
            name: "all"
      source_address6:
         -
            name: "all"

      authentication_rule:
        -
          groups:
            - name: "SSL-GROUP"
          portal: "sslvpn"

              

        

