# Create the different VLANs on an interface
# Configure DCP on those VLANs if needed
# Create address groups accordingly
---
- name: Create VLANs on an interface
  fortios_system_interface:
    enable_log: true
    state: "present"
    system_interface:
      vdom: "{{ vdom }}"
      interface: "{{ item.interface }}"
      type: "vlan"
      vlanid: "{{ item.id }}"
      name: "{{ item.name }}"
      mode: static
      ip: "{{ item.ip }} {{ item.subnet }}"
      allowaccess: "{{ item.allowaccess_list }}"
      role: "lan"
  with_items: "{{ vlans }}"
  when: vlans is defined

- name: Configure DHCP server for VLANs
  fortios_system_dhcp_server:
    enable_log: true
    state: present
    vdom: "{{ vdom }}"
    system_dhcp_server:
      id: "{{ item.id }}"
      interface: "{{ item.interface }}"
      ip_mode: range
      default_gateway: "{{ item.default_gateway }}"
      ip_range:
        - end_ip: "{{ item.end_ip }}"
          id: "{{ item.dhcp_id }}"
          start_ip: "{{ item.start_ip }}"
  with_items: "{{ dhcp_server }}"
  when: dhcp_server is defined

- name: Create address object mactching vlan
  fortios_firewall_address:
    vdom: "{{ vdom }}"
    state: present
    firewall_address:
      allow_routing: enable
      interface: "{{ item.name }}"
      name: "{{ item.name }} address"
      type: "interface-subnet"
  with_items: "{{ vlans }}"
  when: vlans is defined

