#Changes the hostname if the variable is available in the host_vars file of the host
---
- name: Change hostname
  cisco.ios.ios_hostname:
    config:
      hostname: "{{ hostname }}"
  when: hostname is defined