---
- name: Configure static route
  cisco.ios.ios_static_routes:
    config:
      - address_families:
        - afi: ipv4
          routes:
          - dest: "{{ item.dest }}/{{ item.mask }}"
            next_hops:
            - forward_router_address: "{{ item.next_hop }}"
  with_items: "{{ ip_routes }}"
  when: ip_routes is defined
