

- name: IP NAT INSIDE/OUTSIDE on interfaces
  cisco.ios.ios_config:
    before: 
    - interface {{ item.interface }}
    lines:
      - ip nat {{ item.inout }}
    parents: interface {{ item.interface }}
  with_items: "{{ ip_int_nat }}"
  when: ip_int_nat is defined

- name: NAT CONFIG FOR EX1
  cisco.ios.ios_config:
    lines:
      - access-list 1 permit any
      - ip nat inside source list 1 interface FastEthernet0/1 overload
  when: ex1_nat is true

