ansible_host: 192.168.99.3
ansible_user: "admin" 
ansible_become_password: admin
ansible_ssh_pass: admin

#Give Hostname to Router
#hostname: name
hostname: BruInter

#Assign IP to an interface
###TEMPLATE###
#ip_config:
  #interface:
    #ip: "0.0.0.0"
    #subnet: "0.0.0.0"
ip_config:
  FastEthernet0/0:
      ip: "192.168.1.2"
      subnet: "255.255.255.0"

#Create an ip route
###TEMPLATE###
#ip_routes:
  #-dest: IP
  # mask: MASK
  # next_hop: IP


#INTERVLAN ROUTING#
##TEMPLATE##
# interfaces:
# - name: INTERFACE (NOT SUBINTERFACE)
#   subinterfaces:
#     - vlan_id: VLAN_ID
#       ip: IP
#       subnet: SUBNET
#     - vlan_id: VLAN_ID
#       ip: IP
#       subnet: SUBNET

interfaces:
- name: FastEthernet0/0
  subinterfaces:
    - vlan_id: 8
      ip: 192.168.8.1
      subnet: 255.255.255.0
    # - vlan_id: 10
    #   ip: 192.168.10.1
    #   subnet: 255.255.255.0
    # - vlan_id: 99
    #   ip: 192.168.99.1
    #   subnet: 255.255.255.0

##CONFIGURE OSPF
##TEMPLATE##
# ospf_processes:
#   - process_id: PROCESS ID
#     router_id: ROUTER ID
#     default_information:
#       originate: true/false
#     network:
#       - address: IP
#         wildcard_bits: WILDCARD
#         area: AREA
#       - address: IP
#         wildcard_bits: WILDCARD
#         area: AREA


ospf_processes:
  - process_id: 1
    router_id: 1.1.1.1
    default_information:
      originate: true
    network:
      - address: 192.168.2.0
        wildcard_bits: 0.0.0.3
        area: 0

###CONFIGURE DHCP###

##Configure DHCP POOL##
#Template#
# pools:
# - name: NAME
#   subconfigurations:
#     - network: NETWORK (IP SUBNET)
#       default_router: IP

##EXCLUDE DHCP ADDRESSES##
##TEMPLATE##
# dhcp_excluded:
# - "IP"
# - "IP-FROM IP-TO"
  

