# ansible_host: 192.168.99.6
ansible_host: 192.168.99.6
ansible_user: "admin" 
ansible_become_password: admin
ansible_ssh_pass: admin

#Give Hostname to Router
#hostname: name
hostname: BrusselRouter

#If domain_lookup is false no ip domain-lookup command will be executed
domain_lookup: false

#Assign IP to an interface
###TEMPLATE###
#ip_config:
  #interface:
    #ip: "0.0.0.0"
    #subnet: "0.0.0.0"

ip_config:
  Serial0/1/1:
    ip: "192.168.2.2"
    subnet: "255.255.255.252"

clockrate: 
  - interface: Serial0/1/1
    value: "128000"

#Create an ip route
###TEMPLATE###
#ip_routes:
  #-dest: IP
  # mask: MASK
  # next_hop: IP


#INTERVLAN ROUTING#
##TEMPLATE##
# interfaces:
# - name: INTERFACE (NOT SUBINTERFACE)
#   subinterfaces:
#     - vlan_id: VLAN_ID
#       ip: IP
#       subnet: SUBNET
#     - vlan_id: VLAN_ID
#       ip: IP
#       subnet: SUBNET


##CONFIGURE OSPF
##TEMPLATE##
# ospf_processes:
#   - process_id: PROCESS ID
#     router_id: ROUTER ID
#     default_information:
#       originate: true/false
#     network:
#       - address: IP
#         wildcard_bits: WILDCARD
#         area: AREA
#       - address: IP
#         wildcard_bits: WILDCARD
#         area: AREA

ospf_processes:
  - process_id: 1
    router_id: 1.1.1.1
    network:
      - address: 192.168.2.0
        wildcard_bits: 0.0.0.3
        area: 0

###CONFIGURE DHCP###

##Configure DHCP POOL##
#Template#
# pools:
# - name: NAME
#   subconfigurations:
#     - network: NETWORK (IP SUBNET)
#       default_router: IP

pools:
- name: "vlan8"
  subconfigurations:
    - network: "192.168.8.0 255.255.254.0"
      default_router: "192.168.8.1"
- name: "vlan10"
  subconfigurations:
    - network: "192.168.10.0 255.255.255.0"
      default_router: "192.168.10.1"
  
##EXCLUDE DHCP ADDRESSES##
##TEMPLATE##
# dhcp_excluded:
# - "IP"
# - "IP-FROM IP-TO"

dhcp_excluded:
- "192.168.8.1 192.168.8.2"
- "192.168.10.1 192.168.10.2"
- "192.168.99.1 192.168.99.13"
- "192.168.99.99 192.168.99.99"

ip_a_DHCP:
- fastEthernet 0/1

##Configure IP helper address
##TEMPLATE##
# ip_helper:
#   interface: INTERFACE
#   address: IP


#Configure ip nat inside/outside on interfaces
ip_int_nat:
  - interface: Serial0/1/1
    inout: inside
  - interface: FastEthernet0/1
    inout: outside


#Specific configuration for ex1, since NATTING is seen as some advanced network configuration and is for network administrators

ex1_nat: true



