#Configure and IP-adress on an interface
---
- name: Configure interface
  cisco.ios.ios_config:
    before: 
    - interface {{ item }}
    lines:
      - ip address {{ ip_assignement[item].ip_address }}
    after: 
      - no shutdown
    match: strict
    parents: interface {{ item }}
  with_items: "{{ ip_assignement.keys() }}"
  when: ip_assignement is defined

    