
#TODO: vaults



# tasks file for Switches

#Creates a Backup of the running config and puts it in a file at ex1/backups
#- include_tasks: /home/killian/Network-Automation/roles/switches/tasks/backup.yml

#Changes the hostname if the variable is available in the host_vars file of the host
#- include_tasks: /home/killian/Network-Automation/roles/switches/tasks/hostname.yml

#Create VLAN's if vlans variable in group_var is 
#- include_tasks: /home/killian/Network-Automation/roles/switches/tasks/vlans.yml

#Switchport mode trunk on interfaces in colleciton trunk_interfaces
#- include_tasks: /home/killian/Network-Automation/roles/switches/tasks/trunk.yml

#Switchport mode trunk on interfaces in colleciton access_interfaces:
#- include_tasks: /home/killian/Network-Automation/roles/switches/tasks/access.yml

#Assign an IP_address to an interface
# - include_tasks: /home/killian/Network-Automation/roles/switches/tasks/ip_adress.yml

#Assign default-gateway if it's not already present
# - include_tasks: /home/killian/Network-Automation/roles/switches/tasks/default_gateway.yml

# Shutdown all unused ports
- include_tasks: /home/killian/Network-Automation/roles/switches/tasks/shutdown.yml

#Save configuration if something was modified
- include_tasks: /home/killian/Network-Automation/roles/switches/tasks/save_running.yml
