---
- name: Switchport Trunk configuration
  cisco.ios.ios_l2_interfaces:
    config:
    - name: "{{ item }}"
      mode: trunk
      trunk:
        allowed_vlans: "{{ trunk_interfaces[item].allowed_vlans }}"
  with_items: "{{ trunk_interfaces.keys() }}"
  when: trunk_interfaces is defined
  register: switchport_trunk_result