ansible_host: 192.168.99.2
ansible_user: "admin" 
ansible_become_password: admin
ansible_ssh_pass: admin

hostname: ISP

ip_config:
  FastEthernet0/0:
      ip: "193.190.200.2"
      subnet: "255.255.255.252"
  FastEthernet0/1:
      ip: "193.190.200.5"
      subnet: "255.255.255.252"

ospf_processes:
  - process_id: 1
    router_id: 1.1.1.1
    network:
      - address: 193.190.200.0
        wildcard_bits: 0.0.0.3
        area: 0
      - address: 193.190.200.4
        wildcard_bits: 0.0.0.3
        area: 0
